apiVersion: v1
kind: PersistentVolume
metadata:
  name: assets-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: C:\assets
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assets-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
